FROM golang:latest

ADD . /go/src/github.com/michelaquino/check-password

WORKDIR /go/src/github.com/michelaquino/check-password
RUN GOOS=linux GOARCH=amd64 go build cmd/hashcat_runner.go

ENTRYPOINT /go/src/github.com/michelaquino/check-password/hashcat_runner
