version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-main
        ports: 
            - 8888:8888
        depends_on:
            - databaseMongo
        environment:
            - PORT=8888
            - LOG_LEVEL=debug
            - DBAAS_MONGODB_ENDPOINT=mongodb://:@databaseMongo:27017/check-password?replicaSet=
            - MONGO_TIMEOUT=60
    # hashcat-runner:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile-hashcat
    #     depends_on:
    #         - mongodb
    #     environment:
    #         - LOG_LEVEL=debug
    #         - DBAAS_MONGODB_ENDPOINT=mongodb 
    #         - MONGO_PORT=27017 
    #         - MONGO_TIMEOUT=60
    #         - MONGO_DATABASE_NAME=check-password
    databaseMongo:
        image: mongo:3.4.7

# LOG_LEVEL=debug DBAAS_MONGODB_ENDPOINT=mongodb://u_mongo_check_pa:ub3xBg78rX@mongocheck-01-150342212015.mongodb.globoi.com:27017,mongocheck-02-150342212015.mongodb.globoi.com:27017/mongo_check_password_prod?replicaSet=ReplicaSet_mongocheck150342212015